### PR TITLE
charge.dispute.* webhooks describe Disputes, as such the main objects…

### PR DESCRIPTION
**Pull request by iarp**
… ID is the dispute not the Charge.

- New middle class obtains the charge key instead of id

In reference to issue #311

### CODE REVIEW

**Comment by lukeburden** [comment]
@iarp any chance you're going to throw some tests into the mix so this can be merged?

**Comment by iarp** [comment]
I really lost track of this one, sorry about that. We ended up falling back to Paypal as we needed something working asap and stripe fell off. Stripe's back into the picture for us and I'm looking into what I did here..etc. I won't lie, I've never written my own tests for anything and when I look at the current tests written, I really don't know what to do.

**Comment by gregnewman** [comment]
@iarp look in the webhook tests for examples:  https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/tests/test_webhooks.py

**Comment by tstirrat15** [comment]
What's the status on this one? I'd love to see this in master and am willing to help get it in place.

**Comment by tstirrat15** [comment]
Bump

**Comment by blueyed** [comment]
@tstirrat15 
That does not help!
You might want to pick it up yourself instead.

**Comment by iarp** [comment]
The last set of circleci tests all passed with the exception of lint which failed over a single blank line. We've long passed moved on from pinax-stripe and I would very much like to remove the repo from my side. I'm not really sure where to go from here. I added this repo to my remote and wanted to merge master onto the branch but its already up to date.

**Pull request closed without merging**
