### PR TITLE
Fix sync_payment_source_from_stripe_data to not crash with sources

### PR DESCRIPTION
**Pull request by blueyed**
This handles "source" objects now without crashing, but does not create
Card objects from the data therein.

I think that should get done probably?!

Helps with https://github.com/pinax/pinax-stripe/issues/383.

### CODE REVIEW

**Comment by blueyed** [comment]
This is crucial for webhooks to work correctly when using sources that a not plain card objects.

**Comment by blueyed** [comment]
IIRC iOS uses card objects, but with Android you get them wrapped in Source objects.

**Comment by paltman** [comment]
I like the checking against types.  More explicit.  I'm wondering why I didn't do that in the first place, unless at one point back in the early days we didn't have `type`.  Anyway, I'm +1 on this.  Is it still WIP?

**Comment by blueyed** [comment]
It is good to go as is for now.

**Pull request merged**
