### PR TITLE
[RFC] admin: prefetch related fields

### PR DESCRIPTION
**Pull request by blueyed**
This only does it for the customer's changelist view now, but it meant
to be generic enough for other admins.

You can easily see the number of queries going down when using django-debug-toolbar or something similar.

TODO:
 - [x] tests

### CODE REVIEW

**Comment by paltman** [comment]
I'm a 👍 on this.  Can you please use double-quotes is all that I ask, please?

**Comment by blueyed** [comment]
> double-quotes

Sure.  At least you do not have two-space indendation.. ;)

I have some stashed tests to test the number of queries in existing tests - will update.

**Comment by blueyed** [comment]
Tests have been added - but there might be a better way.

**Comment by blueyed** [comment]
Would like some feedback on the tests.
@ticosax @paltman @lukeburden

**Pull request merged**
