### PR TITLE
Add __repr__ methods

### PR DESCRIPTION
**Pull request by blueyed**
This is only done for Plan, Customer and Subscription for now, and open
for discussion.

It helps a lot when debugging and/or looking at locals in tracebacks.

TODO:
- [x] tests

### CODE REVIEW

**Comment by paltman** [comment]
I’m generally in favor of this. 

Any objection to using format() instead of %?

Also style wise I prefer skipping the multi line string, then making the argument list one argument per line as it’s easier to scan.

**Comment by blueyed** [comment]
You mean like
```diff
     def __repr__(self):
-        return ('Plan(pk=%r, name=%r, amount=%r, currency=%r, interval=%r, '
-                'interval_count=%r, trial_period_days=%r, stripe_id=%r)' % (
-                    self.pk, self.name, self.amount, self.currency,
-                    self.interval, self.interval_count,
-                    self.trial_period_days, self.stripe_id))
+        return ('Plan(pk={!r}, name={!r}, amount={!r}, currency={!r}, interval={!r}, '
+                'interval_count={!r}, trial_period_days={!r}, stripe_id={!r})'.format(
+                    self.pk,
+                    self.name,
+                    self.amount,
+                    self.currency,
+                    self.interval,
+                    self.interval_count,
+                    self.trial_period_days,
+                    self.stripe_id))
```

IMHO it makes the whole file harder to scan (by adding more lines).

**Comment by blueyed** [comment]
@paltman 
ping

**Comment by paltman** [comment]
No, more like:

```python
    def __repr__(self):
        return "Plan(pk={!r}, name={!r}, amount={!r}, currency={!r}, interval={!r}, interval_count={!r}, trial_period_days={!r}, stripe_id={!r})".format(
            self.pk,
            self.name,
            self.amount,
            self.currency,
            self.interval,
            self.interval_count,
            self.trial_period_days,
            self.stripe_id
        )
```

**Comment by blueyed** [comment]
Amended and added basic tests.

**Comment by paltman** [comment]
Hit by string string differences in py2 and py3 on the tests.

**Comment by blueyed** [comment]
How to handle this best?

```
AssertionError: "Plan(pk=None, name=u'My Plan', amount=Decimal('5'), currency=u'', interval=u'monthly', interval_count=1, trial_period_days=None, stripe_id=u'')" !=
               u"Plan(pk=None, name='My Plan', amount=Decimal('5'), currency='', interval='monthly', interval_count=1, trial_period_days=None, stripe_id='')"
```

**Comment by blueyed** [comment]
This is really helpul while debugging btw!

**Pull request merged**
