### PR TITLE
Test against PostgreSQL

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Got it working over in https://github.com/lock8/pinax-stripe/pull/22, but there is a failing test, which I'll address next week, and then bring it back here.

**Comment by blueyed** [comment]
Expected to fail, the fix for the test is https://github.com/pinax/pinax-stripe/pull/439.

**Comment by paltman** [comment]
What does changing the database backend give us?  We are not doing anything special in the queries that I would think needs to be validated.

**Comment by blueyed** [comment]
It just ensures that pinax-stripe works with PostgreSQL, which is likely the DB that is used in production the most.
We do not have to use it for all test matrix entries, but it should run at least once.

**Pull request merged**
