### PR TITLE
CircleCI: use postgres user

### PR DESCRIPTION
**Pull request by blueyed**
"root" is not available anymore?!

Ref: https://circleci.com/gh/lock8/pinax-stripe/1256

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, seems to have been some temporary problem?!
At least https://github.com/pinax/pinax-stripe/pull/591 still failed with this commit.
Closing for now.

**Comment by blueyed** [comment]
Seems to be required?! - not sure what happened in https://circleci.com/gh/pinax/pinax-stripe/8542?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link though..

**Comment by jpic** [comment]
We had to hardcode the user too in another project too with a similar setup (python + pg + cci)

**Comment by jpic** [comment]
Note that we also needed to extend wait timeout from 10 secs (as specified by their docs) to 20:

https://github.com/betagouv/mrs/commit/0fba65bdf0cf24913f1c25918c8843e0247bb7ff
https://github.com/betagouv/mrs/commit/09e548038df394176f0602f5dbc2a5b16dd5c348

Then it started working again

**Comment by blueyed** [comment]
@jpic 
Thanks.
Do you know why this is necessary now?  Have the circleci/postgres Docker images changed?

**Comment by blueyed** [comment]
Included in https://github.com/pinax/pinax-stripe/pull/618.

**Comment by blueyed** [comment]
@paltman 
It might make sense to change the codecov/patch status to not being required - it disallows me to merge this at least.
IIRC I've closed/re-opened to get it reported, but without luck apparently.
@codecov is having some issues in this regard since a while.

**Comment by blueyed** [comment]
@paltman 
Thanks, next  would be the "This branch is out-of-date with the base branch" check (like seen above).
Often it is not really necessary to ensure this, and in the unlikely case it would break master it is usually easy to fix.
E.g. in this case it does not really make sense to run CI again, just because a doc typo fix was merged.

**Pull request merged**
