### PR TITLE
commands/sync_customers.py: raise in case it is not a 404

### PR DESCRIPTION
**Pull request by blueyed**
As per https://github.com/pinax/pinax-stripe/commit/5bb5ca0a7d49f2146aa09fc801b7d164129bf45c#commitcomment-24814293.

btw: this was not covered, and I will not cover it.

### CODE REVIEW

**Comment by blueyed** [comment]
@paltman 
What is the expected workflow after you approve things?

It might make sense to have a "PRs to be merged soon" label, which would allow for further review, but then having a good entrypoint for you to actually merge stuff.

**Comment by paltman** [comment]
@blueyed honestly I hadn't needed to think about it for a long time.  the barrage of PRs caught me off guard. :)

I'm currently working on putting together a release [Samwise](https://github.com/pinax/pinax-stripe/milestone/10) and triaging open PRs that don't look very risky to include, so I can focus on getting those merged, writing the release notes, testing things out, and shipping off to PyPI.

**Comment by paltman** [comment]
Tests are failing now though. :(

**Comment by ticosax** [comment]
@paltman We are glad that you are trying to get things moving forward.
We are trying to get stripe connect features working and you can have a look at our current branch.

https://github.com/lock8/pinax-stripe/tree/next

We, so far, backported few changes to upstream to stabilize Connect support, but still some work needs to be considered before calling master stable.
We think by the end of next week we will have something good, quality wise, to support Connect.
I'm discouraging you to make a release against master as it is today, as Connect support is not shippable, mostly in regard of #247 or other PR that touches models. If you make a  release it will be hard to fix stuff without breaking compatibility.
As soon as you merge PRs that we depend on in master we will be able to deliver what is missing quite quickly.
Just give us one more week, rest assured that we will continue to provide support since `pinax-stripe` is a critical dependency of our project.

**Comment by paltman** [comment]
@ticosax sounds good.  I appreciate the help and support.  this is such a big release I want to take our time and get it right.

**Comment by paltman** [comment]
Silly me.

Thanks!

**Comment by paltman** [comment]
How do we handle the migration conflict here?

**Comment by blueyed** [comment]
Merge them? (did so)

**Pull request merged**
