### PR TITLE
Squash 11 migrations related to connect into 1

### PR DESCRIPTION
**Pull request by lukeburden**
#### What's this PR do?

Consolidates a mess of migrations into a single migration, since they're all Account/Connect related.

#### Any background context you want to provide?

I discussed the obvious backward compat issues with this approach with @paltman who agrees we should only be striving for backward compat across actual releases.

### CODE REVIEW

**Comment by ticosax** [comment]
Nice, therefore it is maybe prematurate as #400 and #413 will bring other schema changes. We are waiting for some PR to get merged before submitting other fixes as well.

**Comment by paltman** [comment]
What are you waiting on?  I️ don’t really know what’s blocking what. I️ want to get a release out this week.

**Comment by ticosax** [comment]
> What are you waiting on? 

We are waiting some pending pull requests we depend on to be merged, to submit next steps.

> I️ don’t really know what’s blocking what. I️ want to get a release out this week.

Fine, make the release, just know that connect is not stable yet and other schema changes are expected for a better integration. Everything we think needs to be backported is in #440. That's more or less what's needs to be done. That said, there is no blocker for a release this week, I trust you'll do what is best.

**Comment by paltman** [comment]
Can you give me a list of PRs? Hard for me to tell from that big 440.

**Comment by paltman** [comment]
All I can see is that #440 is a massive PR with 150 commits.  I realize this is intended to be an integration branch, but it's not obvious to me what pull requests are in there that are blocking things.  I'd like to give some attention to them tomorrow so we can get this moving along but I need some help in figuring out what those are.  /cc @ticosax @blueyed

**Comment by blueyed** [comment]
@paltman 
I think it does not really belong here, and we had this discussion at least once already somewhere else.. what about a meta issue?
As for the list, I think it is basically https://github.com/pinax/pinax-stripe/pulls/blueyed and https://github.com/pinax/pinax-stripe/pulls/ticosax, but we're still in the testing phase and there are still more issues that need to be fixed and will turn up.
#440 is not a PR, but meant as an easy way to compare the changes (https://github.com/pinax/pinax-stripe/pull/440/files).

**Comment by blueyed** [comment]
As for the process of squashing the migrations, you might want to actually create a squashed migration on top of the existing ones.
You could then still decide to only ship the squashed migration in the release.

**Comment by blueyed** [comment]
A big change would be the `UserAccount` through model (https://github.com/pinax/pinax-stripe/pull/440/files#diff-90b0e5e37b96af44d789c587800e86c0R234).

**Comment by paltman** [comment]
@blueyed Yes, I remember you had suggested creating a meta issue and I thought I had +1'd it.  I am not really in the position of creating it as I don't know what I'd put in it.  I really am relying on you guys to tell me what needs to be wrapped up for the connect support as I'm not using the feature anywhere yet.

**Comment by paltman** [comment]
I am confused though about you guys saying connect support isn't ready because @lukeburden is using what he's done, so it's at least working for some.

I'd like to focus on getting done for connect support items that will make a subsequent release to tighten it up harder, which the only thing i can really think of is migration work.  I treat `master` as something that can always change and am only really concerned with migrations working between releases.

**Comment by blueyed** [comment]
> not really in the position of creating it as I don't know what I'd put in it.

It can be edited / commented on, right?

> connect support isn't ready because @lukeburden is using what he's done

Well, it depends on what you are using then apparently.. ;)

For example, event processing was broken very hard in case you are using sources (which is done when using the Android SDK).  The same applies to Subscriptions if you are using them with a Connect account, etc.

I/We do not want to block a release of course, we're just trying to help.
Given that you hard-squash all the migrations we'll have to probably keep a fork just because of that anyway then.

**Comment by paltman** [comment]
No, let's avoid you having to maintain a fork.  Are you running off of `master`?  Is that why you'd maintain a fork?

**Comment by blueyed** [comment]
We're running off of `next`.

**Comment by paltman** [comment]
Ok, I'm happy to work with you so you don't have to maintain a fork.  

Are you *only* merging PRs into `next` or are some commits getting pushed directly to that branch?

**Comment by blueyed** [comment]
I am pushing my stuff to "pinax" first as a rule of thumb, but there are things in there based on "next" - a bigger one is Coupons for example and the UserAccounts stuff, of course.
I've pulled some stuff out of there already, but it is messy indeed.

I do not think that it is a problem for us to maintain a fork after all.. - I am trying to push / contribute everything back, but it is very exhausting.

**Comment by blueyed** [comment]
And I will unsubscribe from this PR now: it is not the right place to discuss this.

**Pull request merged**
