### PR TITLE
Account: add publishable_key field

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/pinax/pinax-stripe/issues/437.

### CODE REVIEW

**Comment by blueyed** [comment]
Likely not needed - the ephemeral key seems to be enough after all.

**Comment by paltman** [comment]
@blueyed are you able to update this branch against master and merge the migrations?  If not I might punt this until the `Rosie` release next month.  Trying to get a release buttoned up tomorrow.

**Comment by blueyed** [comment]
@paltman
Updated and merged.

I would suggest waiting until the end of the week at least for the release.  Otherwise it might become problematic with regard to migrations etc, in case there are changes that would need data migrations still.

**Comment by paltman** [comment]
What happens this week?

I have a follow-up milestone, Rosie, due at the end of November to capture any fixes after 4.0.0 (Samwise ships).  There really isn't much left in this (Samwise) milestone.

**Comment by blueyed** [comment]
> What happens this week?

Tomorrow is a holiday in Germany, but then we will keep working on the integration.

We have a mix of #400 / #402 in use (#440) for example, which makes sense to include IMHO.
I think @ticosax might create a separate PR for it, once #427 is merged.
I suggest getting #440 as empty as possible before a release.

It might make sense to create a meta issue to track TODOs for the release, e.g. that migrations should  be squashed (using Django's mechanism).

**Comment by blueyed** [comment]
IMHO there is no reason to rush a release with Stripe Connect integration that is still very bumpy.
You might want to create some smaller bugfix release (without the Connect feature), if that makes sense?!

**Comment by paltman** [comment]
Fair enough.  I relying on feedback from people actually using this feature in practice.  I'm planning to build something with it for myself.  I'm just getting nervous about how big this is becoming.  I'll block any other non-connect related features until after the release.  Do you want to create that issue with the TODOs and we'll add it to Samwise?

**Comment by paltman** [comment]
What else is in #440 besides #400 and #402?

**Pull request merged**
