### PR TITLE
tox: checkqa: check isort via flake8-isort

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Failure can be seen in https://circleci.com/gh/pinax/pinax-stripe/2217.

**Comment by blueyed** [comment]
@paltman 
this is crucial to get PRs green (especially with checkqa being required before tests).

**Comment by paltman** [comment]
A big reason I had avoided flake8-isort was I preferred to keep all the CI config in one place in tox.ini and use the `setup.cfg` for packaging config like the universal wheel attribute.  

Not following why it's critical to use this wrapper tool.

**Comment by blueyed** [comment]
It integrates nicely with running `flake8` yourself locally, e.g. with Neomake in your editor.

**Comment by blueyed** [comment]
I suggest also moving the flake8 config to setup.cfg.

**Comment by paltman** [comment]
I would prefer to do the opposite and move things into tox.ini and leave setup.cfg for packaging.

**Comment by paltman** [comment]
what's the argument for moving things out of tox.ini?

**Comment by blueyed** [comment]
The main argument seems to be that `flake8` does not look at `tox.ini` by default.

I am constantly running into issues where lint complains about single quotes etc (and I get no feedback for the actual tests (see #418)) because of that.
I use Neomake to run `flake8`, but that does not help.

IMHO `setup.cfg` is a good place for config/cfg, while `tox.ini` is very much specific to tox.

**Comment by paltman** [comment]
I have had zero problems with flake8 reading config from tox.ini for years now. 

http://flake8.pycqa.org/en/latest/user/configuration.html

**Comment by blueyed** [comment]
Ok, then it might be just flake8-isort.
But anyway, `setup.cfg` feels like config (look at the `.cfg` and `setup` there).
And you need it for the wheels config anyway.

Feel free to close this if you feel inclinded, but I think having a more config-like central place for configuration is a good trade-off for making flake8-isort work out of the box.

**Comment by blueyed** [comment]
And besides that, config/isort is one of the less important issues of this project currently.

It's just because of open (and addressed in PR) issues like https://github.com/pinax/pinax-stripe/pull/418 that config is important for me to fix - since it is currently very disruptive.

**Comment by blueyed** [comment]
Even here we still see that checks for py{35,36}master are waiting for status to be reported, but I've asked several times already to just remove them from the protected branch.
This would make like 20+ PRs green already, which are currently orange (looking like CI would have hiccups).  But it still takes an extra step to not require PRs for being up to date with master (#422).

**Comment by paltman** [comment]
Fixed the master checking

**Comment by blueyed** [comment]
PRs still have to be up-to-date with master, no?

**Comment by blueyed** [comment]
@paltman 
Would you accept this after all?
Then I would rebase it / fix the conflicts.

**Comment by paltman** [comment]
I thought `flake8-isort` didn't read from tox.ini (thus the need for this PR https://github.com/gforcada/flake8-isort/pull/35/commits/9071dffaddddc865677c6fc9832ac902885f48a0)

**Comment by blueyed** [comment]
This change does not seem to be in flake8-isort yet.
But even if it was in, I still consider `setup.cfg` more the source of tool config (and you need the file anyway).

**Comment by blueyed** [comment]
@paltman 
You have not answered my previous question about taking it when I would fix the conflicts.
Please do so, and close it in case you really want to keep generic config in tox.ini.

**Comment by paltman** [comment]
I'm fine with it now.  Can you resolve the conflicts and I'll get it merged.  I appreciate your patience with me.

**Pull request merged**
