### PR TITLE
Fix Plan.currency: blank=False

### PR DESCRIPTION
**Pull request by blueyed**
currency cannot be blank.

> Stripe currently supports these currencies: usd, aed, afn, all, amd, ang, aoa, ars, aud, awg, azn, bam, bbd, bdt, bgn, bif, bmd, bnd, bob, brl, bsd, bwp, bzd, cad, cdf, chf, clp, cny, cop, crc, cve, czk, djf, dkk, dop, dzd, egp, etb, eur, fjd, fkp, gbp, gel, gip, gmd, gnf, gtq, gyd, hkd, hnl, hrk, htg, huf, idr, ils, inr, isk, jmd, jpy, kes, kgs, khr, kmf, krw, kyd, kzt, lak, lbp, lkr, lrd, lsl, mad, mdl, mga, mkd, mmk, mnt, mop, mro, mur, mvr, mwk, mxn, myr, mzn, nad, ngn, nio, nok, npr, nzd, pab, pen, pgk, php, pkr, pln, pyg, qar, ron, rsd, rub, rwf, sar, sbd, scr, sek, sgd, shp, sll, sos, srd, std, svc, szl, thb, tjs, top, try, ttd, twd, tzs, uah, ugx, uyu, uzs, vnd, vuv, wst, xaf, xcd, xof, xpf, yer, zar, zmw, eek, lvl, vef

Should there be a validator for this?

### CODE REVIEW

**Comment by ticosax** [comment]
needs a rebase

**Comment by blueyed** [comment]
done.

**Comment by paltman** [comment]
Looks done.  Is this still a WIP?

**Comment by blueyed** [comment]
We could have a validator additionally, but then let's create a new issue for it.

**Comment by paltman** [comment]
Will adding the `blank=False` trigger a need for a migration?

**Comment by blueyed** [comment]
You would now with https://github.com/pinax/pinax-stripe/pull/422 ;)

**Comment by blueyed** [comment]
Not according to `python makemigrations.py`.

**Pull request merged**
