### PR TITLE
Amounts are Integers.

### PR DESCRIPTION
**Pull request by ticosax**
[Not mergeable at this point]

This one is a bit scary as I have no idea how to deal with existing projects which have floats in their database...

I never wrote test for data migration powered by django migrations. I don't know if it is feasible.
Any pointer is welcome :smile: 

Anyway, first thing first, are you willing to accept this contribution ? assuming we know how to deal with data migration.

### CODE REVIEW

**Comment by paltman** [comment]
For the reasons stated in #233 ([this comment](https://github.com/pinax/pinax-stripe/pull/223#issuecomment-163333171)), I'd prefer not to go this route.

Happy to continue to discuss this if you feel strongly (I feel strongly to, but I think it's worth hashing it out with the idea of arriving at the best thing so I welcome the challenging of my opinions :smile:)

**Comment by ticosax** [comment]
My main concern here is the correctness for float conversion to integers. relying on `actions` to transform field types imply usage of rounding. Rounding will necessarily introduce some errors. Unlike in #223 we don't deal with simple mapping `None` to `""`.
Rounding can be non-repeatable depending on python version for instance.

Maybe we are lucky all amounts have 0 as decimal, since amounts are cents it could makes sense. So I might be concern for a not real use case.

**Comment by ticosax** [comment]
I just saw you assume amounts in the database are not expressed in `cents` so the conversion is `*100` instead of rounding `4.55` to `4`.

**Comment by paltman** [comment]
Very interesting and I think deserving of some comprehensive tests to make sure we are covering all angles. I thought I had done this already but I'm sure I'm missing things.

**Comment by ticosax** [comment]
This is covered by tests. It is my fault.

**Pull request closed without merging**
