### PR TITLE
models: Account.user: blank=True / remove Account.user

### PR DESCRIPTION
**Pull request by blueyed**
What do you think about removing the user ForeignKey here altogether?

It could then be a FK from your own model, which does not have to be User.

Includes https://github.com/pinax/pinax-stripe/pull/412.

### CODE REVIEW

**Comment by paltman** [comment]
@lukeburden any thoughts on this?

**Comment by lukeburden** [comment]
@paltman at minimum, allowing null/blank user values is a good idea.

As to removing the FK altogether, looking over my implementation, I did not end up being dependent on this direct association between the User model and Accounts. As @blueyed suggests, I ended up using a proxy model, "PayoutMethod", that makes this linkage as well as storing some extra state.

That said, I could see some implementations not using another model and wanting to make the direct linkage.

I see this scenario being pretty similar to the `user` field on the Customer model - it's also nullable, allowing optional usage.

If we want our models in this project to strictly reflect data in Stripe, then we should remove the user fields from both Account and Customer, probably - personally I think optional user fields are a practical middle-ground allowing simple projects to skip creating extra models to make the user linkage.

**Comment by blueyed** [comment]
Thanks for the feedback.
Rebased it.

**Comment by paltman** [comment]
I concur that the optional user FK is a good middle-ground.  I personally use FK to users quite a bit and it would be a pain to have to create an extra model to just link to Customer.

**Comment by paltman** [comment]
@blueyed is this still `RFC`?  or is it ready for merge?

**Comment by blueyed** [comment]
@paltman 
Let's take this as-is then.

**Pull request merged**
