### PR TITLE
create documentation for commands

### LINKED ISSUE #206: Write Reference Docs for Management Commands

### PR DESCRIPTION
**Pull request by cfc603**
Fixes #206

### CODE REVIEW

**Comment by ossanna16** [comment]
@cfc603 Thank you! We have another merge conflict here because your branch isn't up-to-date with master. If you could update it that would be great :)

**Comment by cfc603** [comment]
@ossanna16, all set on this one as well.

**Comment by paltman** [comment]
@cfc603 sorry about this but looks like merging your other PR made this conflict again.  do you mind updating it?  If you can't get to it soon, i think i can take care of it next week.

**Comment by cfc603** [comment]
@paltman, no problem.

**Comment by paltman** [comment]
@cfc603 awesome, thanks!

**Pull request merged**
