### PR TITLE
[RFC] CircleCI: test merge commit

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/pinax/pinax-stripe/issues/415

Source: https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14

### CODE REVIEW

**Comment by blueyed** [comment]
Not too sure about this one anymore: it might cause trouble with Codecov's reporting, where the coverage report is for the merge commit, but Codecov assumes this to be for the commit itself.
This might cause Codecov to think that there are changes created through the PR, although they come from the updated master branch.

**Comment by blueyed** [comment]
To keep things simple we might want to revert this.

**Comment by paltman** [comment]
@blueyed whatever you think is best.  I was just trusting you on it as I didn't quite follow the issue and didn't have the time to investigate to learn. :)

**Comment by blueyed** [comment]
Let's keep it for now then, but have an eye on it.
I am waiting for feedback from Codecov in this regard - I imagine that there is some special code in this regard server-side, since Travis also tests the merge commit by default.

**Pull request merged**
