### PR TITLE
Fix CustomerUpdatedWebhook: do not call sync_customer without customer

### PR DESCRIPTION
**Pull request by blueyed**
Otherwise the `if customer.date_purged` in `customers.sync_customer`
fails.

The alternative might be to actually try fetching the customer, but I do
not think a local customer should be created, if it failed before, or
was deleted etc?!

### CODE REVIEW

**Comment by blueyed** [comment]
I will cover the patch once approved in general.

**Comment by blueyed** [comment]
It is valid wrt to "customer.deleted" at least.

**Comment by blueyed** [comment]
@paltman 
?

**Comment by paltman** [comment]
This seems good to me.

**Pull request merged**
