### PR TITLE
[RDY] better support for running tests in pytest

### PR DESCRIPTION
**Pull request by blueyed**
I plan to make using pytest more easy with this project.

What is your opinion on using it by default?

### CODE REVIEW

**Comment by blueyed** [comment]
@paltman 
Any input on this?

Some more local changes I have, but for that it would be good to know your opinion on using pytest by default:

```diff
diff --git a/setup.py b/setup.py
index 4384e32..e58f10e 100644
--- a/setup.py
+++ b/setup.py
@@ -53,6 +53,12 @@
 recurring subscriptions managed by Stripe.
 """
 
+tests_require = [
+    "mock",
+    "django_forms_bootstrap",
+]
+
+
 setup(
     name=NAME,
     author=AUTHOR,
@@ -89,10 +95,10 @@
         "pytz",
         "six",
     ],
+    extras_require={
+        "pytest": ["pytest", "pytest-django"] + tests_require,
+    },
     test_suite="runtests.runtests",
-    tests_require=[
-        "mock",
-        "django_forms_bootstrap",
-    ],
+    tests_require=tests_require,
     zip_safe=False,
 )
```

```diff
diff --git a/tox.ini b/tox.ini
index 216d309..f30eb7a 100644
--- a/tox.ini
+++ b/tox.ini
@@ -24,6 +24,9 @@ deps =
     1.10: Django>=1.10,<1.11
     1.11: Django>=1.11a1,<2.0
     master: https://github.com/django/django/tarball/master
+    # tests_require
+    mock
+    django_forms_bootstrap
 usedevelop = True
 setenv =
    LANG=en_US.UTF-8
```

**Comment by paltman** [comment]
I like what you did here, moving the settings to live as a module under the tests package and I'm ready to make that a standard across all our pinax apps.

I'm not sure about making pytest default right now.  I put a high value on keeping a standard practice across all of Pinax so when we _break the mold_ I want to consider things very carefully.

What is the benefit of pytest over the built-in test runner?

**Comment by blueyed** [comment]
> What is the benefit of pytest over the built-in test runner?

test selection, a bunch of useful plugins etc.

Anyway, I see your point, and will change this to only allow for using pytest easily, but not making it the default.

**Comment by blueyed** [comment]
Should be ready from my side.
Please review.

**Comment by paltman** [comment]
I started to resolve conflicts but not sure what you were going for in tox.ini.  I've only used it on Travis to run multiple parallel tests.  Now that we are on CircleCi which has built-in support for matrices, I dropped a lot of that in tox.ini.

**Comment by blueyed** [comment]
Rebased.

**Comment by blueyed** [comment]
Ping.

btw: how do you run a single test currently?

**Comment by paltman** [comment]
@blueyed I don't.  I run all of them.  Literally, takes seconds.

**Comment by blueyed** [comment]
It is quite annoying though after a while, and would not be necessary with this being merged - so that it is easy to use pytest.
What is holding this back?

**Comment by ticosax** [comment]
This is painful to not be able to select which test we'd like to run.
I'd really like to see it merged.

**Comment by paltman** [comment]
Nothing in particular. Just lots of things going on and not just in this repo.

**Comment by blueyed** [comment]
@paltman 
Thanks, it's a relief!

You should really check out pytest btw.. :)

**Pull request merged**
