### PR TITLE
Fix typo `customer` in connect.md

### PR DESCRIPTION
**Pull request by josh91hickman**
#### What's this PR do?
Fixes a typo in the `connect.md` documentation

#### Any background context you want to provide?
spent a few minutes debugging this with a copy/paste, will be helpful for future users

#### What ticket or issue # does this fix?
N/A

Closes #[issue number]
N/A

#### Definition of Done (check if considered and/or addressed):

- [ ] Are all backwards incompatible changes documented in this PR?
- [ ] Have all new dependencies been documented in this PR?
- [ X ] Has the appropriate documentation been updated (if applicable)?
- [ ] Have you written tests to prove this change works (if applicable)?

[ci skip]

### CODE REVIEW

**Comment by blueyed** [comment]
@paltman 
Why not just merge it right away?
For the build failure see https://github.com/pinax/pinax-stripe/pull/592.

**Comment by paltman** [comment]
@blueyed oh, I thought I'd let you test out your new merge "bit"

**Comment by blueyed** [comment]
Thank you for your contribution!

**Comment by josh91hickman** [comment]
np!

**Pull request merged**
