### PR TITLE
Increase limit on invoice item syncing

### PR DESCRIPTION
**Pull request by davelowe**
Stripe provides 10 invoice items by default; increase this to 100 (barring a new setting)

### CODE REVIEW

**Comment by davelowe** [comment]
Yes, exactly. We have invoice item data in `stripe_invoice[“lines”]` but it’s only the first page of items (Stripe paginates by 10). So items after that first 10 will never be synced unless we explicitly ask Stripe for more lines.

**Review by paltman — APPROVED** [review]
Good deal. Thanks!

I wonder if we shouldn't eventually pagination through until the end.

**Comment by davelowe** [comment]
Yeah, there’s the inherent weakness that an order could exceed the number of items we’re requesting. I wasn’t convinced the extra code was worth it since even the 10 item limit seems to be working for nearly everyone, but paginating through would be the right move eventually (and especially if we can paginate by more than 10).

**Comment by paltman** [comment]
@davelowe the failing tests I think are from the need to now mock the `stripe.Invoice.retrieve` call.  There should be examples of these in the test suites.  Can you fix that up so I can merge this?  I'd love to get it in a release that I hope to get out today.  Thanks!

**Comment by paltman** [comment]
@davelowe just pinging you again in case the first message was lost.  do you think you could fix up that test soon?

**Comment by davelowe** [comment]
Glad you did! I never saw the first for some reason. Sure, I'll try to get a fix in today for that.

**Comment by paltman** [comment]
@davelowe any luck getting that test fix up in?

**Pull request closed without merging**
